import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common'; import { prisma, AccountRole, DeliveryStatus, NotificationSeverity, OutboxEventStatus, Prisma } from '@alzad/db'; import { ApiError } from '../../common/api-error'; import type { AuthContext } from '../auth/auth.types'; import { SettingsService } from '../settings/settings.service'; import { addRiyadhWorkingHours } from '../settings/business-day.util';
@Injectable() export class NotificationsService implements OnModuleInit,OnModuleDestroy { private timer?:NodeJS.Timeout; constructor(private readonly settings:SettingsService){}
  onModuleInit(){this.timer=setInterval(()=>{void this.runWorker().catch(()=>undefined)},60_000);this.timer.unref()}
  onModuleDestroy(){if(this.timer)clearInterval(this.timer)}
  async list(ctx:AuthContext){const where:Prisma.NotificationWhereInput=ctx.role===AccountRole.ADMIN?{OR:[{accountId:ctx.accountId},{audienceRole:AccountRole.ADMIN}]}:ctx.role===AccountRole.ASSOCIATION?{OR:[{accountId:ctx.accountId},{associationId:ctx.associationId,audienceRole:AccountRole.ASSOCIATION}]}:{accountId:ctx.accountId};return prisma.notification.findMany({where,orderBy:{createdAt:'desc'},take:200})}
  async markRead(ctx:AuthContext,id:string){const items=await this.list(ctx);if(!items.some(n=>n.id===id))throw new ApiError('NOTIFICATION_NOT_FOUND','الإشعار غير موجود',404);return prisma.notification.update({where:{id},data:{readAt:new Date()}})}
  async runWorker(){await this.processOutbox();await this.scanDeliverySla();return{ok:true}}
  async processOutbox(){return prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext('notification-outbox-worker'))`;const events=await tx.outboxEvent.findMany({where:{status:OutboxEventStatus.PENDING},orderBy:{createdAt:'asc'},take:100});for(const event of events){const p=event.payload as Record<string,unknown>;const associationId=typeof p.associationId==='string'?p.associationId:null;const target=describe(event.type);await tx.notification.upsert({where:{dedupeKey:`outbox:${event.id}`},create:{associationId,audienceRole:target.role,type:String(event.type),title:target.title,body:target.body,severity:target.severity,entityType:'outbox_events',entityId:event.id,dedupeKey:`outbox:${event.id}`},update:{}});await tx.outboxEvent.update({where:{id:event.id},data:{status:OutboxEventStatus.PROCESSED,processedAt:new Date(),attempts:{increment:1},lastError:null}})}return{processed:events.length}})}
  async scanDeliverySla(){const [workingDays,holidays,reminder,first,second,critical]=await Promise.all([this.settings.getValue<number[]>('calendar.workingDays'),this.settings.getValue<string[]>('calendar.holidays'),this.settings.getValue<number>('sla.approvalReminderHours'),this.settings.getValue<number>('sla.zaadFirstAlertHours'),this.settings.getValue<number>('sla.zaadSecondAlertHours'),this.settings.getValue<number>('sla.criticalOverdueHours')]);if(!workingDays||!holidays||[reminder,first,second,critical].some(v=>typeof v!=='number'))return{skipped:'required SLA/calendar settings missing'};const missions=await prisma.deliveryMission.findMany({where:{status:DeliveryStatus.PENDING_DELIVERY_APPROVAL},select:{id:true,associationId:true,updatedAt:true}});const now=new Date();const tiers=[['approval-reminder',reminder!,NotificationSeverity.WARNING],['zaad-first',first!,NotificationSeverity.WARNING],['zaad-second',second!,NotificationSeverity.WARNING],['critical',critical!,NotificationSeverity.CRITICAL]] as const;for(const m of missions)for(const[tier,hours,severity]of tiers)if(addRiyadhWorkingHours(m.updatedAt,hours,{workingDays,holidays})<=now)await prisma.notification.upsert({where:{dedupeKey:`sla:${m.id}:${tier}`},create:{associationId:m.associationId,audienceRole:tier==='approval-reminder'?AccountRole.ASSOCIATION:AccountRole.ADMIN,type:'DELIVERY_APPROVAL_SLA',title:'تنبيه مهلة اعتماد التسليم',body:`مهمة التسليم ${m.id} تجاوزت مهلة ${tier}`,severity,entityType:'delivery_missions',entityId:m.id,dedupeKey:`sla:${m.id}:${tier}`},update:{}});return{scanned:missions.length}}
}
function describe(type:string){if(type==='DELIVERY_SUBMITTED')return{role:AccountRole.ASSOCIATION,title:'تسليم بانتظار اعتماد الجمعية',body:'أرسل المندوب إثبات التسليم وتوقيع المستفيد.',severity:NotificationSeverity.INFO};if(type==='DELIVERY_ASSOCIATION_APPROVED')return{role:AccountRole.ADMIN,title:'تسليم بانتظار اعتماد زاد',body:'اعتمدت الجمعية التسليم وهو جاهز للاعتماد النهائي.',severity:NotificationSeverity.WARNING};if(type==='RETURN_REQUESTED')return{role:AccountRole.ASSOCIATION,title:'طلب إرجاع بانتظار الاستلام الفعلي',body:'طلب المندوب إرجاع العهدة؛ لا تُحرر قبل التأكيد المادي.',severity:NotificationSeverity.WARNING};if(type==='ESCALATION_OPENED')return{role:AccountRole.ADMIN,title:'تصعيد تشغيلي جديد',body:'يوجد تصعيد يحتاج قرار زاد.',severity:NotificationSeverity.WARNING};return{role:AccountRole.ADMIN,title:'حدث تشغيلي',body:`حدث جديد: ${type}`,severity:NotificationSeverity.INFO}}
