import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import request from 'supertest';
import type { Response } from 'superagent';
import type { INestApplication } from '@nestjs/common';
import { DeleteObjectCommand } from '@aws-sdk/client-s3';
import { AccountRole, AccountStatus, AgreementStatus, AssociationSelectionList, AuthCredentialType, ParticipationStatus, prisma } from '@alzad/db';
import { createTestApp } from './utils/bootstrap';
import { cleanAuthState, hashSecret, seedTestFixtures } from './utils/fixtures';
import { loginAs, loginAsDelegate } from './utils/node2-fixtures';
import { startTestStorage, stopTestStorage, storageClient, testBucket } from './utils/storage-harness';
import { COVENANT_SOURCE_SHA256 } from '../src/modules/participations/covenant-document.service';
import type { FakeEmailService } from '../src/modules/auth/email/fake-email.service';

describe('Covenant V1 execution gate', () => {
  let fakeEmail: FakeEmailService;
  let app: INestApplication; let adminCookie = ''; let otherAssociationCookie = ''; let delegateCookie = ''; let associationCookie = ''; let abanmiCookie = '';
  let applicationId = ''; let participationId = ''; let agreementId = ''; let associationId = ''; let accountId = ''; let abanmiAccountId = '';
  let temporaryPassword = ''; const currentPassword = 'Covenant!Current2026'; let partyOneToken = ''; let finalSha256 = '';
  const signature = readFileSync(join(process.cwd(), 'test', 'assets', 'synthetic-signature.png'));
  const http = () => request(app.getHttpServer()); const opId = (label: string) => `${label}-${randomUUID()}`;

  beforeAll(async () => {
    await startTestStorage(); ({ app, fakeEmail } = await createTestApp()); const fixtures = await seedTestFixtures();
    adminCookie = await loginAs(app, fixtures.adminEmail, fixtures.adminPassword); otherAssociationCookie = await loginAs(app, fixtures.assocEmail, fixtures.assocPassword); delegateCookie = await loginAsDelegate(app, fixtures.delegateCode);
    const suffix = randomUUID().slice(0, 8); const email = `covenant-${suffix}@example.org`;
    const application = await prisma.associationApplication.create({ data: { publicCode: `E2E-COV-${suffix}`, clientRequestId: `e2e-cov-${suffix}`, name: `جمعية ميثاق تجريبية ${suffix}`, category: 'جمعية خيرية', sector: 'رعاية الأيتام', region: 'الرياض', city: 'الرياض', phone: `055${Math.floor(Math.random() * 10_000_000).toString().padStart(7, '0')}`, email, contactName: 'ممثل ميثاق تجريبي', pledgeAccepted: true, pledgeAcceptedAt: new Date(), selectionList: AssociationSelectionList.MAIN } }); applicationId = application.id;
    const participation = await prisma.projectParticipation.create({ data: { applicationId, status: ParticipationStatus.APPROVED_AWAITING_SETUP, activationBasis: 'AGREEMENT_COMPLETED', setupCompletedAt: new Date(), setupCompletedById: (await prisma.account.findFirstOrThrow({ where: { email: fixtures.adminEmail } })).id } }); participationId = participation.id;
    const created = await http().post(`/api/v1/participations/${participationId}/agreements`).set('Cookie', adminCookie).send({ version: 1, templateVersion: '1.0' }).expect(201); agreementId = created.body.id;
    await http().post(`/api/v1/participations/agreements/${agreementId}/transition`).set('Cookie', adminCookie).send({ status: AgreementStatus.SENT, opId: opId('sent') }).expect(201);
    const accountOperation = opId('account');
    const prepared = await http().post(`/api/v1/participations/${participationId}/signing-account`).set('Cookie', adminCookie).send({ opId: accountOperation }).expect(201); temporaryPassword = prepared.body.temporaryPassword; associationId = prepared.body.associationId; accountId = prepared.body.accountId;
    expect(fakeEmail.lastSecurityAlert).toMatchObject({ to: email, subject: 'بيانات دخول الجمعية — مشروع الأجهزة الكهربائية' });
    expect(fakeEmail.lastSecurityAlert!.body).toContain(temporaryPassword);
    expect(fakeEmail.lastSecurityAlert!.body).toContain('/login');
    fakeEmail.lastSecurityAlert = null;
    const replay = await http().post(`/api/v1/participations/${participationId}/signing-account`).set('Cookie', adminCookie).send({ opId: accountOperation }).expect(201);
    expect(replay.body.temporaryPassword).toBeNull();
    expect(fakeEmail.lastSecurityAlert).toBeNull();
    const emailAudits = await prisma.auditLog.findMany({ where: { entityId: accountId, action: 'ASSOCIATION_CREDENTIALS_EMAIL_SENT' } });
    expect(emailAudits).toHaveLength(1);
    expect(JSON.stringify(emailAudits)).not.toContain(temporaryPassword);
    abanmiAccountId = (await prisma.account.create({ data: { publicCode: `E2E-ABN-COV-${suffix}`, name: 'أبانمي اختبار الميثاق', email: `abanmi-cov-${suffix}@example.org`, role: AccountRole.ABANMI, status: AccountStatus.ACTIVE } })).id;
    await prisma.authCredential.create({ data: { accountId: abanmiAccountId, type: AuthCredentialType.EMAIL_PASSWORD, identifier: `abanmi-cov-${suffix}@example.org`, secretHash: await hashSecret('Abanmi!Covenant2026') } });
    abanmiCookie = await loginAs(app, `abanmi-cov-${suffix}@example.org`, 'Abanmi!Covenant2026');
  }, 90000);

  afterAll(async () => {
    const agreement = agreementId ? await prisma.participationAgreement.findUnique({ where: { id: agreementId }, select: { fileId: true, orgSignatureFileId: true, partyOneSignatureFileId: true, finalFileId: true } }) : null;
    const fileIds = agreement ? [agreement.fileId, agreement.orgSignatureFileId, agreement.partyOneSignatureFileId, agreement.finalFileId].filter((id): id is string => Boolean(id)) : [];
    const objects = fileIds.length > 0 ? await prisma.fileObject.findMany({ where: { id: { in: fileIds } }, select: { objectKey: true } }) : [];
    await cleanAuthState(); await prisma.idempotencyKey.deleteMany({}); await prisma.participationAgreement.deleteMany({ where: { id: agreementId } }); await prisma.projectParticipation.deleteMany({ where: { id: participationId } }); await prisma.associationApplication.deleteMany({ where: { id: applicationId } });
    await prisma.authCredential.deleteMany({ where: { accountId: { in: [accountId, abanmiAccountId] } } }); await prisma.account.deleteMany({ where: { id: { in: [accountId, abanmiAccountId] } } }); await prisma.association.deleteMany({ where: { id: associationId } }); await prisma.fileObject.deleteMany({ where: { id: { in: fileIds } } });
    for (const item of objects) await storageClient().send(new DeleteObjectCommand({ Bucket: testBucket(), Key: item.objectKey }));
    await app.close(); await stopTestStorage();
  }, 60000);

  it('1. eligible restricted Association account can login', async () => { const response = await http().post('/api/v1/auth/login').send({ type: 'user', email: (await prisma.account.findUniqueOrThrow({ where: { id: accountId } })).email, password: temporaryPassword }).expect(200); expect(response.body.user.covenantRequired).toBe(true); });
  it('2. temporary credential requires first password change', async () => { const response = await http().post('/api/v1/auth/login').send({ type: 'user', email: (await prisma.account.findUniqueOrThrow({ where: { id: accountId } })).email, password: temporaryPassword }).expect(200); const cookie = cookieOf(response); await http().get('/api/v1/beneficiaries').set('Cookie', cookie).expect(403).expect(({ body }) => expect(body.error.code).toBe('AUTH_PASSWORD_CHANGE_REQUIRED')); await http().patch('/api/v1/auth/password').set('Cookie', cookie).send({ currentPassword: temporaryPassword, newPassword: currentPassword }).expect(200); });
  it('3. password change revokes the prior session and old temporary password', async () => { await http().post('/api/v1/auth/login').send({ type: 'user', email: (await prisma.account.findUniqueOrThrow({ where: { id: accountId } })).email, password: temporaryPassword }).expect(401); const response = await http().post('/api/v1/auth/login').send({ type: 'user', email: (await prisma.account.findUniqueOrThrow({ where: { id: accountId } })).email, password: currentPassword }).expect(200); associationCookie = cookieOf(response); expect(response.body.user.mustChangePassword).toBe(false); });
  it('4. unsigned Association is explicitly marked for the Covenant Gate', async () => { const me = await http().get('/api/v1/auth/me').set('Cookie', associationCookie).expect(200); expect(me.body).toMatchObject({ covenantRequired: true, covenantStatus: 'SENT' }); });
  it('5. direct operational API is server-blocked before execution', async () => { await http().get('/api/v1/beneficiaries').set('Cookie', associationCookie).expect(403).expect(({ body }) => expect(body.error.code).toBe('COVENANT_EXECUTION_REQUIRED')); });
  it('6. Covenant V1 version, source hash, and restricted frame policy are canonical', async () => { const view = await http().get('/api/v1/participations/covenant').set('Cookie', associationCookie).expect(200); expect(view.body).toMatchObject({ version: '1.0', sourceSha256: COVENANT_SOURCE_SHA256, status: 'SENT' }); const template = await http().get('/api/v1/participations/covenant/template').set('Cookie', associationCookie).buffer(true).parse(binaryParser).expect(200); expect(createHash('sha256').update(template.body).digest('hex').toUpperCase()).toBe(COVENANT_SOURCE_SHA256); expect(template.headers['x-frame-options']).toBeUndefined(); expect(template.headers['content-security-policy']).toBe('frame-ancestors http://localhost:3000'); expect(template.headers['cache-control']).toContain('no-store'); });
  it('7. missing authorization acknowledgement is rejected', async () => { await covenantSignRequest({ authorized: false, accepted: true, password: currentPassword }).expect(400).expect(({ body }) => expect(body.error.code).toBe('COVENANT_AUTHORIZATION_REQUIRED')); });
  it('8. missing acceptance acknowledgement is rejected', async () => { await covenantSignRequest({ authorized: true, accepted: false, password: currentPassword }).expect(400).expect(({ body }) => expect(body.error.code).toBe('COVENANT_ACCEPTANCE_REQUIRED')); });
  it('9. missing handwritten signature is rejected', async () => { await http().post('/api/v1/participations/covenant/sign').set('Cookie', associationCookie).field('representativeName', 'ممثل الجمعية التجريبي').field('representativeTitle', 'المدير التنفيذي').field('authorizedAcknowledgement', 'true').field('acceptanceAcknowledgement', 'true').field('currentPassword', currentPassword).field('opId', opId('missing-signature')).expect(400).expect(({ body }) => expect(body.error.code).toBe('COVENANT_SIGNATURE_REQUIRED')); });
  it('9b. a padded tiny JPEG cannot bypass server-side signature dimensions', async () => { const tinyJpeg = Buffer.alloc(800); Buffer.from([0xff, 0xd8, 0xff, 0xc0, 0x00, 0x11, 0x08, 0x00, 0x01, 0x00, 0x01]).copy(tinyJpeg); await http().post('/api/v1/participations/covenant/sign').set('Cookie', associationCookie).field('representativeName', 'ممثل الجمعية التجريبي').field('representativeTitle', 'المدير التنفيذي').field('authorizedAcknowledgement', 'true').field('acceptanceAcknowledgement', 'true').field('currentPassword', currentPassword).field('opId', opId('tiny-signature')).attach('signature', tinyJpeg, { filename: 'tiny.jpg', contentType: 'image/jpeg' }).expect(400).expect(({ body }) => expect(body.error.code).toBe('COVENANT_SIGNATURE_DIMENSIONS_INVALID')); });
  it('10. invalid current-password confirmation is rejected', async () => { await covenantSignRequest({ authorized: true, accepted: true, password: 'Wrong!Password2026' }).expect(400).expect(({ body }) => expect(body.error.code).toBe('COVENANT_PASSWORD_INVALID')); });
  it('11. valid Association handwritten signature succeeds', async () => { await covenantSignRequest({ authorized: true, accepted: true, password: currentPassword }).expect(201).expect(({ body }) => expect(body.status).toBe('SIGNED_BY_ORG')); });
  it('12. the Association cannot rewrite its signed record', async () => { await covenantSignRequest({ authorized: true, accepted: true, password: currentPassword }).expect(409); });
  it('13. Association B cannot access Association A covenant', async () => { await http().get(`/api/v1/participations/agreements/${agreementId}/final`).set('Cookie', otherAssociationCookie).expect(403); });
  it('14. Party-One signing-session issuance is ADMIN-only', async () => { await http().post(`/api/v1/participations/agreements/${agreementId}/party-one-session`).set('Cookie', associationCookie).expect(403); });
  it('15. Party-One completion cannot be forged through the legacy transition API', async () => { await http().post(`/api/v1/participations/agreements/${agreementId}/transition`).set('Cookie', adminCookie).send({ status: AgreementStatus.SIGNED, signerName: 'مزور', opId: opId('forge') }).expect(400); });
  it('16. random Party-One tokens are denied', async () => { await http().get(`/api/v1/participations/covenant/party-one/${'x'.repeat(43)}`).expect(403); });
  it('17. protected Party-One signing session shows the correct covenant', async () => { const issued = await http().post(`/api/v1/participations/agreements/${agreementId}/party-one-session`).set('Cookie', adminCookie).expect(201); partyOneToken = issued.body.token; const view = await http().get(`/api/v1/participations/covenant/party-one/${partyOneToken}`).expect(200); expect(view.body).toMatchObject({ version: '1.0', status: 'SIGNED_BY_ORG', associationRepresentative: 'ممثل الجمعية التجريبي' }); await http().get(`/api/v1/participations/covenant/party-one/${partyOneToken}/association-signature`).expect(200); });
  it('18. Delegate and ABANMI cannot access authenticated covenant evidence', async () => { await http().get('/api/v1/participations/covenant').set('Cookie', delegateCookie).expect(403); await http().get('/api/v1/participations/covenant').set('Cookie', abanmiCookie).expect(403); });
  it('19. exactly one concurrent Party-One handwritten signature fully executes the covenant', async () => { const attempts = await Promise.all([http().post(`/api/v1/participations/covenant/party-one/${partyOneToken}/sign`).field('opId', opId('party-one-a')).attach('signature', signature, { filename: 'synthetic-signature.png', contentType: 'image/png' }), http().post(`/api/v1/participations/covenant/party-one/${partyOneToken}/sign`).field('opId', opId('party-one-b')).attach('signature', signature, { filename: 'synthetic-signature.png', contentType: 'image/png' })]); expect(attempts.map(({ status }) => status).sort()).toEqual([201, 403]); const accepted = attempts.find(({ status }) => status === 201)!; expect(accepted.body.status).toBe('SIGNED'); finalSha256 = accepted.body.finalSha256; });
  it('20. the single-use Party-One token cannot be reused', async () => { await http().post(`/api/v1/participations/covenant/party-one/${partyOneToken}/sign`).field('opId', opId('reuse')).attach('signature', signature, { filename: 'synthetic-signature.png', contentType: 'image/png' }).expect(403); });
  it('21. FULLY_EXECUTED opens Association operations', async () => { const relogin = await http().post('/api/v1/auth/login').send({ type: 'user', email: (await prisma.account.findUniqueOrThrow({ where: { id: accountId } })).email, password: currentPassword }).expect(200); associationCookie = cookieOf(relogin); expect(relogin.body.user.covenantRequired).toBe(false); await http().get('/api/v1/beneficiaries').set('Cookie', associationCookie).expect(200); });
  it('22. own final covenant is authorized and the stored hash is stable', async () => { const first = await http().get('/api/v1/participations/covenant/final').set('Cookie', associationCookie).expect(200); const second = await http().get('/api/v1/participations/covenant/final').set('Cookie', associationCookie).expect(200); expect(first.body.sha256).toBe(finalSha256); expect(second.body.sha256).toBe(finalSha256); const bytes = Buffer.from(await (await fetch(first.body.url)).arrayBuffer()); expect(createHash('sha256').update(bytes).digest('hex')).toBe(finalSha256); expect(bytes.subarray(0, 5).toString('ascii')).toBe('%PDF-'); });
  it('23. raw private signature/object access is not exposed by an unauthenticated application route', async () => { await http().get(`/api/v1/participations/agreements/${agreementId}/final`).expect(401); const record = await prisma.participationAgreement.findUniqueOrThrow({ where: { id: agreementId }, include: { orgSignatureFile: true } }); expect(record.orgSignatureFile?.objectKey).toMatch(/^covenants\/signatures\/association\//); });
  it('24. covenant audit records contain no password, raw signature, or token', async () => { const rows = await prisma.auditLog.findMany({ where: { entityId: agreementId, action: { startsWith: 'COVENANT_' } } }); expect(rows.map((row) => row.action)).toEqual(expect.arrayContaining(['COVENANT_ASSOCIATION_SIGNED', 'COVENANT_PARTY_ONE_SIGNED', 'COVENANT_FULLY_EXECUTED'])); expect(JSON.stringify(rows)).not.toContain(currentPassword); expect(JSON.stringify(rows)).not.toContain(partyOneToken); });
  it('25. signed Covenant V1 cannot be overwritten or replaced', async () => { await http().post(`/api/v1/participations/${participationId}/agreements`).set('Cookie', adminCookie).send({ version: 1, templateVersion: '1.0' }).expect(409).expect(({ body }) => expect(body.error.code).toBe('COVENANT_VERSION_EXISTS')); await covenantSignRequest({ authorized: true, accepted: true, password: currentPassword }).expect(409); const stored = await prisma.participationAgreement.findUniqueOrThrow({ where: { id: agreementId } }); expect(stored.finalSha256).toBe(finalSha256); });

  function covenantSignRequest(input: { authorized: boolean; accepted: boolean; password: string }) { return http().post('/api/v1/participations/covenant/sign').set('Cookie', associationCookie).field('representativeName', 'ممثل الجمعية التجريبي').field('representativeTitle', 'المدير التنفيذي').field('authorizedAcknowledgement', String(input.authorized)).field('acceptanceAcknowledgement', String(input.accepted)).field('currentPassword', input.password).field('opId', opId('association-sign')).attach('signature', signature, { filename: 'synthetic-signature.png', contentType: 'image/png' }); }
});

function cookieOf(response: request.Response) { const raw = response.headers['set-cookie'] as unknown as string[]; return raw[0].split(';')[0]; }
function binaryParser(response: Response, callback: (error: Error | null, body?: Buffer) => void) { const chunks: Buffer[] = []; response.on('data', (chunk: Buffer) => chunks.push(chunk)); response.on('end', () => callback(null, Buffer.concat(chunks))); response.on('error', (error) => callback(error)); }
