import type { AdminPermission } from '@alzad/shared';

/** Exact registered method/path contracts. Unknown restricted ADMIN routes deny. */
export const ADMIN_ROUTE_POLICIES: Readonly<Record<string, AdminPermission | 'self' | 'owner'>> = {
  'GET /auth/me': 'self', 'POST /auth/logout': 'self', 'PATCH /auth/password': 'self',
  'GET /accounts/admins': 'owner', 'POST /accounts/admins': 'owner',
  'PATCH /accounts/admins/:id': 'owner', 'PATCH /accounts/admins/:id/status': 'owner',
  'POST /accounts/admins/:id/reset-password': 'owner',
  'GET /accounts/abanmi': 'abanmi.manage', 'POST /accounts/abanmi': 'abanmi.manage',
  'POST /auth/associations/:id/reset-password': 'associations.manage',
  'GET /dashboard/admin': 'dashboard.read',
  'GET /association-applications': 'applications.read',
  'GET /association-applications/:id': 'applications.read',
  'GET /association-applications/:id/license-file': 'applications.read',
  'GET /association-applications/:id/eligibility-evidence': 'applications.read',
  'POST /association-applications/selection/preview': 'applications.read',
  'POST /association-applications/:id/review': 'owner',
  'POST /association-applications/processing/start': 'applications.review',
  'POST /association-applications/:id/eligibility': 'applications.review',
  'POST /association-applications/:id/eligibility/resend-rejection': 'applications.review',
  'POST /association-applications/:id/information-request': 'applications.review',
  'POST /association-applications/:id/information-request/resend': 'applications.review',
  'POST /association-applications/:id/evaluation': 'applications.evaluate',
  'POST /association-applications/:id/selection-decision': 'applications.select',
  'POST /association-applications/:id/selection-decision/resend': 'applications.select',
  'POST /association-applications/selection/commit': 'owner',
  'GET /associations': 'associations.read', 'GET /associations/:id': 'associations.read',
  'POST /associations': 'associations.manage', 'PATCH /associations/:id': 'associations.manage',
  'GET /beneficiaries': 'beneficiaries.read', 'GET /beneficiaries/:id': 'beneficiaries.read',
  'GET /beneficiaries/import/template.xlsx': 'beneficiaries.read',
  'POST /beneficiaries/import/preview-xlsx': 'beneficiaries.manage',
  'POST /beneficiaries/import': 'beneficiaries.manage', 'POST /beneficiaries': 'beneficiaries.manage',
  'POST /beneficiaries/bulk-review': 'beneficiaries.manage', 'PATCH /beneficiaries/:id': 'beneficiaries.manage',
  'PATCH /beneficiaries/:id/location': 'beneficiaries.manage', 'POST /beneficiaries/:id/review': 'beneficiaries.manage',
  'POST /beneficiaries/:id/list-decision': 'beneficiaries.manage', 'POST /beneficiaries/:id/promote-reserve': 'beneficiaries.manage',
  'POST /beneficiaries/:id/replace': 'beneficiaries.manage', 'DELETE /beneficiaries/needs/:needId': 'beneficiaries.manage',
  'GET /delegates': 'delegates.read', 'GET /delegates/:id': 'delegates.read',
  'POST /delegates': 'delegates.manage', 'PATCH /delegates/:id': 'delegates.manage',
  'POST /delegates/:id/status': 'delegates.manage', 'POST /delegates/:id/regenerate-code': 'delegates.manage',
  'GET /inventory/devices': 'inventory.read', 'GET /inventory/devices/:id': 'inventory.read',
  'PATCH /inventory/devices/:id': 'inventory.manage', 'POST /inventory/devices/:id/mark-damaged': 'inventory.manage',
  'GET /inventory/damage-cases': 'inventory.read', 'POST /inventory/damage-cases/:id/decision': 'inventory.manage',
  'GET /central-stock': 'inventory.read', 'POST /central-stock/contract': 'inventory.manage', 'POST /central-stock/receipts': 'inventory.manage',
  'GET /receipts': 'receipts.read', 'GET /receipts/:id': 'receipts.read',
  'GET /receipts/:id/evidence/:evidenceType': 'receipts.read',
  'POST /receipts': 'receipts.manage', 'POST /receipts/:id/send': 'receipts.manage',
  'GET /deliveries': 'deliveries.read', 'GET /deliveries/:id': 'deliveries.read',
  'GET /deliveries/attempts/:attemptId/proof': 'deliveries.read', 'GET /deliveries/attempts/:attemptId/signature': 'deliveries.read',
  'POST /deliveries/assign': 'deliveries.manage', 'POST /deliveries/:id/retry': 'deliveries.manage',
  'POST /deliveries/:id/return': 'deliveries.manage', 'POST /deliveries/:id/zaad-approval': 'deliveries.manage',
  'POST /deliveries/:id/reschedule': 'deliveries.manage', 'POST /deliveries/:id/resume': 'deliveries.manage',
  'POST /deliveries/:id/admin-return-override': 'deliveries.manage',
  'GET /procurement/orders': 'procurement.read', 'POST /procurement/orders': 'procurement.manage',
  'POST /procurement/orders/:id/transition': 'procurement.manage', 'POST /procurement/shipments': 'procurement.manage',
  'POST /procurement/shipments/:id/transition': 'procurement.manage', 'POST /procurement/reconciliation-issues/:id/decision': 'procurement.manage',
  'GET /allocation/_module-status': 'allocation.read', 'GET /allocation/baskets': 'allocation.read', 'POST /allocation/run': 'allocation.manage',
  'GET /escalations': 'escalations.read', 'POST /escalations': 'escalations.manage', 'POST /escalations/:id/decision': 'escalations.manage',
  'GET /activities': 'activities.read', 'POST /activities': 'activities.manage', 'POST /activities/catalog/import': 'activities.manage',
  'GET /audit': 'audit.read', 'POST /reference-values': 'reference.manage',
  'GET /settings': 'settings.manage', 'PUT /settings': 'settings.manage', 'GET /settings/_module-status': 'settings.manage',
  'GET /notifications': 'notifications.manage', 'POST /notifications/:id/read': 'notifications.manage',
  'GET /notifications/outbox': 'notifications.manage', 'POST /notifications/process': 'notifications.manage',
  'POST /notifications/operations/step1-completion': 'notifications.manage',
  'GET /participations': 'participations.read', 'GET /participations/agreements/:id/final': 'participations.read',
  'POST /participations/:id/agreements': 'participations.manage', 'POST /participations/agreements/:id/transition': 'participations.manage',
  'POST /participations/:id/signing-account': 'participations.manage', 'POST /participations/agreements/:id/party-one-session': 'participations.manage',
  'POST /participations/:id/setup-complete': 'participations.manage', 'POST /participations/:id/activate': 'participations.manage',
  'POST /participations/:id/coordinator-change': 'participations.manage', 'POST /participations/coordinator-changes/:id/decision': 'participations.manage',
  'GET /reports/abanmi': 'reports.read', 'GET /reports/admin': 'reports.read',
  'GET /reports/abanmi/export.xlsx': 'reports.read', 'GET /reports/admin/export.xlsx': 'reports.read',
  'GET /reports/reconciliation/:associationId': 'reports.read', 'GET /reports/closure/readiness/:participationId': 'reports.read',
  'GET /reports/closure/project': 'reports.read', 'POST /reports/closure/organization/:id/transition': 'reports.manage',
  'POST /reports/closure/organization/:id/reopen': 'reports.manage', 'POST /reports/closure/project/generate': 'reports.manage',
  'POST /reports/closure/project/transition': 'reports.manage',
};

export function adminRoutePolicy(method: string, registeredPath: string | undefined) {
  if (!registeredPath) return undefined;
  // Express supplies the matched route template; IDs and query input cannot alter policy.
  const path = registeredPath.replace(/^\/api\/v1(?=\/|$)/, '');
  return ADMIN_ROUTE_POLICIES[`${method.toUpperCase()} ${path}`];
}
