'use client';
import { useCallback, useEffect, useState } from 'react';
import { AppShell } from '../../components/AppShell'; import { useRoleGuard } from '../../lib/use-role-guard'; import { apiFetch, commitApplicationSelection, decideApplicationEligibility, evaluateApplication, previewApplicationSelection, type ApplicationSummary, type Paginated, type WorkflowRecord } from '../../lib/api'; import { cardStyle, errorStyle, inputStyle, primaryButtonStyle, secondaryButtonStyle, successStyle } from '../../lib/ui';
export default function SelectionPage() { const { user, loading } = useRoleGuard(['ADMIN']); const [apps, setApps] = useState<ApplicationSummary[]>([]); const [preview, setPreview] = useState<WorkflowRecord[]>([]); const [target, setTarget] = useState(''); const [reference, setReference] = useState(''); const [message, setMessage] = useState('');
 const load = useCallback(async () => { try { const result = await apiFetch<Paginated<ApplicationSummary>>('/association-applications?page=1&pageSize=100'); setApps(result.items); } catch (e) { setMessage(e instanceof Error ? e.message : 'تعذر التحميل'); } }, []); useEffect(() => { if (user) void load(); }, [user, load]); if (loading || !user) return null;
 async function run(action: () => Promise<unknown>) { setMessage(''); try { await action(); setMessage('تم حفظ القرار.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'تعذر التنفيذ'); } }
 function score(id: string) { const names = ['operationalReadiness','technicalCapability','previousExperience','integrityTransparency','participationCommitment','sustainabilityImpact','geographicProjectNeed'] as const; const values: Record<string, number> = {}; for (const name of names) { const value = window.prompt(`${name} (0-100)`); if (value === null) return; values[name] = Number(value); } void run(() => evaluateApplication(id, values as Parameters<typeof evaluateApplication>[1])); }
 return <AppShell user={user}><h1>الأهلية والتقييم والاختيار</h1>{message && <p style={message.startsWith('تم') ? successStyle : errorStyle}>{message}</p>}<section style={cardStyle}><p>الأوزان مثبتة خادميًا (30/20/20/15/10/5). حد الاجتياز يُقرأ من الإعدادات ولا يوجد له افتراض.</p>{apps.map((app) => <div key={app.id} style={{ borderTop: '1px solid var(--line)', padding: 10 }}><b>{app.name}</b> <code>{app.publicCode}</code><div><button style={secondaryButtonStyle} onClick={() => run(() => decideApplicationEligibility(app.id, 'PASSED'))}>مجتاز أهلية</button> <button style={secondaryButtonStyle} onClick={() => score(app.id)}>إدخال التقييم</button></div></div>)}</section><section style={cardStyle}><h2>القائمة النهائية</h2><button style={secondaryButtonStyle} onClick={() => run(async () => { const result = await previewApplicationSelection(); setPreview(result.items); })}>معاينة الترتيب</button>{preview.map((row) => <p key={row.id}>{String(row.rank)}. {String(row.name)} — {String(row.score)}</p>)}<input style={inputStyle} type="number" min="1" placeholder="عدد MAIN" value={target} onChange={(e) => setTarget(e.target.value)} /><input style={inputStyle} placeholder="مرجع موافقة الداعم" value={reference} onChange={(e) => setReference(e.target.value)} /><button style={primaryButtonStyle} disabled={!target || !reference.trim()} onClick={() => run(() => commitApplicationSelection(Number(target), reference))}>اعتماد MAIN / RESERVE</button></section></AppShell>;
}
